config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :projects do
    resources :feed, controller: :messages
  end

  root to: redirect(path: '/projects', status: 302)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :messages
  has_many :project_status_logs

  enum status: {
    draft: 0,
    in_progress: 1,
    closed: -1,
    archived: -2
  }

  after_create :log_status
  before_update :log_status, if: -> { status_changed? }

  private

  def log_status
    project_status_logs.create(status: status)
  end
end

app/models/project_status_log.rb
class ProjectStatusLog < ApplicationRecord
  enum status: {
    draft: 0,
    in_progress: 1,
    closed: -1,
    archived: -2
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = current_user.messages.new(message_params)

    respond_to do |format|
      format.turbo_stream do
        if @message.save
          render turbo_stream: turbo_stream.append('messages', partial: "messages/message", locals: { message: @message })
        else
          render :edit, status: :unprocessable_entity
        end
      end

    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        # format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        # format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:body).merge(
        params.permit(:project_id)
      )
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
    @messages = @project.messages.last(25)

    @status_logs = @project.project_status_logs.limit(10)

    if @messages.any?
      @status_logs = @status_logs.where(
        "created_at > ?", @messages.first.created_at
      )
    end

    @events = @messages + @status_logs
    @events.sort_by!(&:created_at)

    @message = Message.new
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.fetch(:project, {}).permit(:name, :description, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_status_badge(project)
    classes = ["badge"]

    classes << case project.status
    when "draft"
      "badge-ghost"
    when "in_progress"
      "badge-primary"
    when "closed"
      "badge-secondary"
    when "archived"
      "badge-neutral"
    end

    content_tag(:div, class: classes) do
      project.status.upcase
    end
  end
end

app/views/layouts/_navbar.html.erb
<nav class="bg-gray-800">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button-->
        <button type="button" class="inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <!--
            Icon when menu is closed.

            Menu open: "hidden", Menu closed: "block"
          -->
          <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <!--
            Icon when menu is open.

            Menu open: "block", Menu closed: "hidden"
          -->
          <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex flex-shrink-0 items-center">
          <img class="block h-8 w-auto lg:hidden" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
          <img class="hidden h-8 w-auto lg:block" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
        </div>
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->

            <%= link_to "Projects", projects_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
          </div>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <button type="button" class="rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
          <span class="sr-only">View notifications</span>
          <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
          </svg>
        </button>

        <!-- Profile dropdown -->
        <% if current_user %>
          <div class="dropdown dropdown-end">
            <label tabindex="0" class="btn btn-ghost btn-circle avatar">
              <div class="w-10 rounded-full">
                <img src="https://railsdevs.com/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEVtIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b230e7fcf12556ad24d7381ec35144676c72d1b3/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RkhKbGMybDZaVjkwYjE5c2FXMXBkRnNIYVFHQWFRR0EiLCJleHAiOm51bGwsInB1ciI6InZhcmlhdGlvbiJ9fQ==--b6239751a398ec468311e69677a9e2a95ada751d/avatar.jpg" />
              </div>
            </label>
            <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
              <li>
                <a class="justify-between">
                  Profile
                  <span class="badge">New</span>
                </a>
              </li>
              <li><a>Settings</a></li>
              <li><%= button_to("Log Out",
                                destroy_user_session_path,
                                method: :delete ) %></li>
            </ul>
          </div>
        <% else %>
          <%= link_to "Sign in", new_user_session_path, class: 'btn btn-default' %>
        <% end %>
      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div class="sm:hidden" id="mobile-menu">
    <div class="space-y-1 px-2 pt-2 pb-3">
      <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->

      <%= link_to "Projects", projects_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | HomeyTest
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
  body
    = render 'layouts/navbar'
    main.container.mx-auto.mt-8.px-5
      / p.notice = notice
      / p.alert  = alert
      = yield

app/views/messages/_form.html.slim
= form_with(model: @message, url: project_feed_index_path(@project)) do |form|
  - if @message.errors.any?
    div style="color: red"
      h2 = "#{pluralize(@message.errors.count, "error")} prohibited this message from being saved:"
      ul
        - @message.errors.each do |error|
          li = error.full_message

  .flex.flex-row.w-full
    = form.text_field :body, placeholder: "Enter comment", class: "w-full focus:outline-none focus:placeholder-gray-400 text-gray-600 placeholder-gray-600 pl-12 bg-gray-200 rounded-md py-3", autocomplete: "off"
    = form.submit "Send", class: "inline-flex items-center justify-center rounded-lg px-4 py-3 transition duration-500 ease-in-out text-white bg-blue-500 hover:bg-blue-400 focus:outline-none float-right"

app/views/messages/_message.html.erb
<% belongs_to_current_user = message.user == current_user %>

<% message_alignment = belongs_to_current_user ? "" : "justify-end" %>
<% avatar = belongs_to_current_user ? "https://railsdevs.com/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEVtIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b230e7fcf12556ad24d7381ec35144676c72d1b3/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RkhKbGMybDZaVjkwYjE5c2FXMXBkRnNIYVFHQWFRR0EiLCJleHAiOm51bGwsInB1ciI6InZhcmlhdGlvbiJ9fQ==--b6239751a398ec468311e69677a9e2a95ada751d/avatar.jpg" : 'https://images.unsplash.com/photo-1590031905470-a1a1feacbb0b?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp' %>

<% balloon_color = belongs_to_current_user ? "bg-gray-300 text-gray-600" : "bg-blue-600 text-white" %>

<div class="chat-message">
  <div class="flex items-end <%= message_alignment %>">
    <div class="flex flex-col space-y-2 text-xs max-w-xs mx-2 order-2 items-start">
        <div>
          <span class="flex"><%= l message.created_at, format: :short %></span>
          <span class="px-4 py-2 rounded-lg inline-block rounded-bl-none <%= balloon_color %>"><%= message.body %></span>
        </div>
    </div>
    <img src="<%= avatar %>?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=facearea&amp;facepad=3&amp;w=144&amp;h=144" alt="My profile" class="w-6 h-6 rounded-full order-1">
  </div>
</div>

app/views/messages/edit.html.slim
h1 Editing message

== render "form", message: @message

br

div
  => link_to "Show this message", @message
  '|
  =< link_to "Back to messages", messages_path

app/views/messages/index.html.slim
p style="color: green" = notice

h1 Messages

#messages
  - @messages.each do |message|
    == render message
    p
      = link_to "Show this message", message

= link_to "New message", new_message_path

app/views/messages/new.html.slim
h1 New message

== render "form", message: @message

br

div
  = link_to "Back to messages", messages_path

app/views/messages/show.html.slim
p style="color: green" = notice

== render @message

div
  => link_to "Edit this message", edit_message_path(@message)
  '|
  =< link_to "Back to messages", messages_path

  = button_to "Destroy this message", @message, method: :delete

app/views/project_status_logs/_event.html.slim
.status-change
  .flex.text-xs
    span = l event.created_at, format: :short
    span.mt-4
      | Status changed to:
      = event.status.camelize

app/views/projects/_form.html.slim
= form_with(model: @project) do |form|
  - if @project.errors.any?
    div style="color: red"
      h2 = "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      ul
        - @project.errors.each do |error|
          li = error.full_message

  div

    = form.label :name, class: "text-gray-500 font-bold"
    = form.text_field :name, class: "mt-1 block w-full rounded-md shadow-sm focus:ring focus:ring-indigo-200 focus:ring-opacity-50"

    = form.label :description, class: "text-gray-500 font-bold"
    = form.text_area :description, class: "mt-1 block w-full rounded-md shadow-sm focus:ring focus:ring-indigo-200 focus:ring-opacity-50"

    = form.label :status, class: "text-gray-500 font-bold"
    = form.select :status, options_from_collection_for_select(Project.statuses, :first, :first, project.status), {}, class: "mt-1 block w-full rounded-md shadow-sm focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
    .mt-4
      = form.submit class: 'btn btn-primary'

app/views/projects/_message_feed.html.slim
.flex-1.p:2.sm:p-6.justify-between.flex.flex-col.h-screen[data-controller="message-feed"]
   #messages.flex.flex-col.space-y-4.p-3.overflow-y-auto.scrollbar-thumb-blue.scrollbar-thumb-rounded.scrollbar-track-blue-lighter.scrollbar-w-2.scrolling-touch
      - @events.each do |event|
         - if event.is_a?(Message)
            = render partial: "messages/message", locals: { message: event }
         - else
            = render partial: "project_status_logs/event", locals: { event: event }


   .px-4.pt-4.mb-2.sm:mb-0
      = form_with(model: @message,
                  url: project_feed_index_path(@project),
                  data: { action: "turbo:submit-end->message-feed#clear_and_scroll"}) do |form|
         - if @message.errors.any?
            div style="color: red"
               h2 = "#{pluralize(@message.errors.count, "error")} prohibited this message from being saved:"
               ul
               - @message.errors.each do |error|
                  li = error.full_message

         .flex.flex-row.w-full
            = form.text_field :body, placeholder: "Enter comment", class: "w-full focus:outline-none focus:placeholder-gray-400 text-gray-600 placeholder-gray-600 pl-12 bg-gray-200 rounded-md py-3", autocomplete: "off"
            = form.submit "Send", class: "inline-flex items-center justify-center rounded-lg px-4 py-3 transition duration-500 ease-in-out text-white bg-blue-500 hover:bg-blue-400 focus:outline-none float-right"

app/views/projects/_project.html.slim
div id="#{dom_id project}"
  .float-right
    = link_to "Edit", edit_project_path(@project), class: 'btn'
  .prose.mb-16
    h3 = project.name.upcase
    = project_status_badge(project)

  .grid.grid-cols-6.gap-4
    .lg:col-span-2
        p = project.description
    .lg:col-span-4
      .prose
        h4 Message Feed
        = render 'message_feed', project: project

app/views/projects/edit.html.slim
.prose
  h3 Editing project

== render "form", project: @project

= link_to "< Back to projects", projects_path, class: "text-gray-500 font-extralight"

app/views/projects/index.html.slim
p style="color: green" = notice

.prose.mb-6
  h1  Projects

#projects.grid.grid-cols-2.gap-4
  - @projects.each do |project|
    div id="#{dom_id project}"
      .prose
        h3 = project.name
      p = project.description.truncate(200)
      p = project_status_badge(project)
      p
        = link_to "Show this project", project, class: "font-medium text-blue-600 dark:text-blue-500 hover:underline"

.mt-8
  = link_to "New project", new_project_path, class: "btn btn-primary"

app/views/projects/new.html.slim
h1.mb-4.text-3xl.font-bold New project

== render "form", project: @project

br

= link_to "< Back to projects", projects_path, class: "text-gray-500 font-extralight"

app/views/projects/show.html.slim
p style="color: green" = notice

== render @project

div
  .mb-4
    = link_to "< Back to projects", projects_path, class: "text-gray-500 font-extralight"

  = button_to "Delete", @project, method: :delete, class: 'btn btn-sm btn-outline btn-error'